language: node_js
node_js:
- 10.15.3
install:
- npm install

env:
  global:
  - CC_TEST_REPORTER_ID=e3ffc172c72c7be2858e053639c49499d31fb8242188c683d5422e5fd95409d5
  - NODE_ENV=test

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE testdb_test_user;' -U postgres
  - sequelize db:migrate

script:
    - npm test

after_success:
  - npm run coveralls
